### ISSUE TITLE
کوئری مربوط به ساخت منوها و صفحات مربوطه هم ایجاد شود

### ISSUE THREAD

**Issue by milanifard** [milanifard/LeitnerBox#1]
مشابه FAQManager

**Comment by uttaparsa** [comment]
کوئری های مرتبط با صدف به جهت آسان تر کردن نصب، افزوده گردیدند.

**Comment by RezaMohajer** [comment]
![image](https://user-images.githubusercontent.com/71932671/107336000-dcca0880-6acd-11eb-814e-cde96416665c.png)
اصلاح شد
دستورات اضافه شدن صفحات مربوطه، به دیتابیس صدف در مرحله چهارم نصّاب اضافه شد .
