### ISSUE TITLE
راهنمای نصب پیچیده است

### ISSUE THREAD

**Issue by milanifard** [milanifard/LeitnerBox#2]
دقیقتر بیان شود

**Comment by uttaparsa** [comment]
سعی شد توضیحات بیشتری به راهنمای نصب اضافه گردد علاوه  بر انتقال اقدامات مربوط به اضافه کردن صفحات به لیست کوئری ها

**Comment by RezaMohajer** [comment]
![image](https://user-images.githubusercontent.com/71932671/107333612-f87fdf80-6aca-11eb-80b9-736dd68b5e11.png)
اصلاح شد. 
(installer.hta) یک نصّاب برای نصب راحت پروژه نوشته شد
