### ISSUE TITLE
نحوه کار نادرست است

### ISSUE THREAD

**Issue by milanifard** [milanifard/LeitnerBox#3]
در جعبه لایتنر جواب از کاربر گرفته نمی شود فقط پرسیده می شود آیا جواب را می داند یا نه. و اگر نمی داند در همان بخش بماند و اگر می داند به بخش بعد می رود. یک دکمه هم برای مشاهده پاسخ داشته باشد.

**Comment by papaparsa** [comment]
با توجه به ذکر نشدن این مورد در جزییات پروژه سعی کردیم تعاملی ترین حالت را با توجه به واقعیت جعبه لایتنر در نظر بگیریم.
هرچند تغییر این مورد نیز پس از بررسی و تحقیق نیاز کاربران چندان دشوار نیست و نیازی به تغییر زیرساختی در نرم افزار نمی باشد.

**Comment by papaparsa** [comment]
changed in acc6baa03b36d37fb41b2763bcdd8fc358ac3c97
